# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Updates to the changelog
on:
  pull_request:
jobs:
  happened:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: "Monitor energy usage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Check for logged changes
        run: git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }} | grep ^CHANGELOG.md$
