name: Makes valid measurements

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkup:
    name: Inspect the code health
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Install dependencies
        run: nix develop -c go get
      - name: Build binary
        run: nix develop -c make build
      - name: Check formatting
        run: nix develop -c test -z $(gofmt -l $(find . -name '*.go'))
      - name: Run tests
        run: nix develop -c go test -v ./...

  measurement:
    name: Monitor energy usage
    needs: checkup
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Clean the environment
        run: nix develop -c make clean
      - name: Prepare the program
        run: nix develop -c make build
      - name: Sleep for a short while
        run: ./etime sleep 4
        env:
          EMPORIA_DEVICE: ${{ secrets.EMPORIA_DEVICE }}
          EMPORIA_USERNAME: ${{ secrets.EMPORIA_USERNAME }}
          EMPORIA_PASSWORD: ${{ secrets.EMPORIA_PASSWORD }}
      - name: Sleep for a bit longer
        run: ./etime sleep 12
        env:
          EMPORIA_DEVICE: ${{ secrets.EMPORIA_DEVICE }}
          EMPORIA_USERNAME: ${{ secrets.EMPORIA_USERNAME }}
          EMPORIA_PASSWORD: ${{ secrets.EMPORIA_PASSWORD }}
